import { useMemo, useState } from "react";
import { cn } from "@/lib/utils";
import { Badge, Field, GhostButton, Input, PageWrap, PrimaryButton, Select } from "./primitives";
import { SAMPLES } from "@/data/openelis";
import {
  Activity,
  BarChart3,
  ClipboardList,
  Download,
  FileSpreadsheet,
  FileText,
  History,
  Printer,
} from "lucide-react";

type ReportKind =
  | "patient-status"
  | "statistics"
  | "by-date"
  | "referred-out"
  | "by-lab-number"
  | "by-patient-id"
  | "csv-export"
  | "audit-trail"
  | "intermediate-service"
  | "nonconformity-notification";

type ReportItem = {
  id: string;
  title: string;
  group: string;
  source: "Routine" | "Study";
  route: string;
  kind: ReportKind;
  description: string;
};

const REPORTS: ReportItem[] = [
  {
    id: "patientCILNSP_vreduit",
    title: "Patient Status Report",
    group: "Status Report",
    source: "Routine",
    route: "/RoutineReport?type=patient&report=patientCILNSP_vreduit",
    kind: "patient-status",
    description: "Patient-level printable report by date, accession range, requester, and result state.",
  },
  {
    id: "statisticsReport",
    title: "Statistics Report",
    group: "Aggregate Reports",
    source: "Routine",
    route: "/RoutineReport?type=indicator&report=statisticsReport",
    kind: "statistics",
    description: "Annual indicator report filtered by lab unit, priority, and reception time frame.",
  },
  {
    id: "indicatorHaitiLNSPAllTests",
    title: "Test Summary",
    group: "Aggregate Reports",
    source: "Routine",
    route: "/RoutineReport?type=indicator&report=indicatorHaitiLNSPAllTests",
    kind: "by-date",
    description: "All-tests summary for a selected date range and lab section.",
  },
  {
    id: "indicatorCDILNSPHIV",
    title: "HIV Test Summary",
    group: "Aggregate Reports",
    source: "Routine",
    route: "/RoutineReport?type=indicator&report=indicatorCDILNSPHIV",
    kind: "by-date",
    description: "HIV-focused indicator summary using the same OpenELIS date-range workflow.",
  },
  {
    id: "sampleRejectionReport",
    title: "Sample Rejection Report",
    group: "Rejection Reports",
    source: "Routine",
    route: "/RoutineReport?type=indicator&report=sampleRejectionReport",
    kind: "by-date",
    description: "Rejected samples grouped by reason, requester, and laboratory unit.",
  },
  {
    id: "activityReportByTest",
    title: "Activity Report by Test",
    group: "Activity Reports",
    source: "Routine",
    route: "/RoutineReport?type=indicator&report=activityReportByTest",
    kind: "by-date",
    description: "Workload activity grouped by individual test.",
  },
  {
    id: "activityReportByPanel",
    title: "Activity Report by Panel",
    group: "Activity Reports",
    source: "Routine",
    route: "/RoutineReport?type=indicator&report=activityReportByPanel",
    kind: "by-date",
    description: "Workload activity grouped by panel.",
  },
  {
    id: "activityReportByTestSection",
    title: "Activity Report by Unit",
    group: "Activity Reports",
    source: "Routine",
    route: "/RoutineReport?type=indicator&report=activityReportByTestSection",
    kind: "by-date",
    description: "Workload activity grouped by laboratory section or unit.",
  },
  {
    id: "referredOut",
    title: "Referred Out Tests Report",
    group: "Referred Tests",
    source: "Routine",
    route: "/RoutineReport?type=patient&report=referredOut",
    kind: "referred-out",
    description: "External referral report filtered by date range and referral organization.",
  },
  {
    id: "haitiNonConformityByDate",
    title: "Nonconformity by Date",
    group: "Nonconformity Reports",
    source: "Routine",
    route: "/RoutineReport?type=patient&report=haitiNonConformityByDate",
    kind: "by-date",
    description: "Nonconforming events summarized across a date range.",
  },
  {
    id: "haitiNonConformityBySectionReason",
    title: "Nonconformity by Unit / Reason",
    group: "Nonconformity Reports",
    source: "Routine",
    route: "/RoutineReport?type=patient&report=haitiNonConformityBySectionReason",
    kind: "by-date",
    description: "Nonconforming events grouped by laboratory unit and reason.",
  },
  {
    id: "ExportWHONETReportByDate",
    title: "Delayed Validation",
    group: "Delayed Validation",
    source: "Routine",
    route: "/RoutineReport?type=patient&report=ExportWHONETReportByDate",
    kind: "by-date",
    description: "Delayed validation report generated by date range.",
  },
  {
    id: "CISampleRoutineExport",
    title: "Routine CSV Export",
    group: "CSV Export",
    source: "Routine",
    route: "/RoutineReport?type=routine&report=CISampleRoutineExport",
    kind: "by-date",
    description: "Routine sample data export for downstream CSV workflows.",
  },
  {
    id: "auditTrail",
    title: "Audit Trail Report",
    group: "Audit Trail",
    source: "Routine",
    route: "/RoutineReport?type=routine&report=auditTrail",
    kind: "audit-trail",
    description: "Accession-level audit history for changes, result edits, and report events.",
  },
  {
    id: "patientARVInitial1",
    title: "ARV Initial Report 1",
    group: "ARV Reports",
    source: "Study",
    route: "/StudyReport?type=patient&report=patientARVInitial1",
    kind: "by-lab-number",
    description: "ARV initial patient report generated by lab number range.",
  },
  {
    id: "patientARVInitial2",
    title: "ARV Initial Report 2",
    group: "ARV Reports",
    source: "Study",
    route: "/StudyReport?type=patient&report=patientARVInitial2",
    kind: "by-lab-number",
    description: "Second ARV initial report format generated by lab number range.",
  },
  {
    id: "patientARVFollowup1",
    title: "ARV Follow-up Report 1",
    group: "ARV Reports",
    source: "Study",
    route: "/StudyReport?type=patient&report=patientARVFollowup1",
    kind: "by-lab-number",
    description: "ARV follow-up report generated by lab number range.",
  },
  {
    id: "patientARVFollowup2",
    title: "ARV Follow-up Report 2",
    group: "ARV Reports",
    source: "Study",
    route: "/StudyReport?type=patient&report=patientARVFollowup2",
    kind: "by-lab-number",
    description: "Second ARV follow-up report format generated by lab number range.",
  },
  {
    id: "patientARV1",
    title: "ARV Initial / Follow-up",
    group: "ARV Reports",
    source: "Study",
    route: "/StudyReport?type=patient&report=patientARV1",
    kind: "by-lab-number",
    description: "Combined ARV report format generated by accession range.",
  },
  {
    id: "patientEID1",
    title: "EID Report 1",
    group: "EID Reports",
    source: "Study",
    route: "/StudyReport?type=patient&report=patientEID1",
    kind: "patient-status",
    description: "EID report with patient, site, lab number, and date filters.",
  },
  {
    id: "patientEID2",
    title: "EID Report 2",
    group: "EID Reports",
    source: "Study",
    route: "/StudyReport?type=patient&report=patientEID2",
    kind: "by-lab-number",
    description: "Second EID report generated by lab number range.",
  },
  {
    id: "patientVL1",
    title: "Viral Load National Report",
    group: "Viral Load",
    source: "Study",
    route: "/StudyReport?type=patient&report=patientVL1",
    kind: "patient-status",
    description: "Viral load patient report by date, accession range, and requester.",
  },
  {
    id: "patientIndeterminate1",
    title: "Intermediate Report 1",
    group: "Intermediate Reports",
    source: "Study",
    route: "/StudyReport?type=patient&report=patientIndeterminate1",
    kind: "by-lab-number",
    description: "Intermediate study report by accession range.",
  },
  {
    id: "patientIndeterminate2",
    title: "Intermediate Report 2",
    group: "Intermediate Reports",
    source: "Study",
    route: "/StudyReport?type=patient&report=patientIndeterminate2",
    kind: "by-lab-number",
    description: "Second intermediate report by accession range.",
  },
  {
    id: "patientIndeterminateByLocation",
    title: "Intermediate by Service",
    group: "Intermediate Reports",
    source: "Study",
    route: "/StudyReport?type=patient&report=patientIndeterminateByLocation",
    kind: "intermediate-service",
    description: "Intermediate report by date range and requester/service location.",
  },
  {
    id: "patientSpecialReport",
    title: "Special Request Report",
    group: "Special Request",
    source: "Study",
    route: "/StudyReport?type=patient&report=patientSpecialReport",
    kind: "by-lab-number",
    description: "Special-request report by accession range.",
  },
  {
    id: "patientCollection",
    title: "Collected ARV Patient Report",
    group: "Patient Reports",
    source: "Study",
    route: "/StudyReport?type=patient&report=patientCollection",
    kind: "by-patient-id",
    description: "Collected ARV patients found by national or patient identifier.",
  },
  {
    id: "patientAssociated",
    title: "Associated Patient Report",
    group: "Patient Reports",
    source: "Study",
    route: "/StudyReport?type=patient&report=patientAssociated",
    kind: "by-patient-id",
    description: "Associated patient report found by national or patient identifier.",
  },
  {
    id: "retroCINonConformityByDate",
    title: "Study Nonconformity by Date",
    group: "Study Nonconformity",
    source: "Study",
    route: "/StudyReport?type=patient&report=retroCINonConformityByDate",
    kind: "by-date",
    description: "Study nonconformity summary across a date range.",
  },
  {
    id: "retroCInonConformityBySectionReason",
    title: "Study Nonconformity by Unit / Reason",
    group: "Study Nonconformity",
    source: "Study",
    route: "/StudyReport?type=patient&report=retroCInonConformityBySectionReason",
    kind: "by-date",
    description: "Study nonconformities grouped by lab unit and reason.",
  },
  {
    id: "retroCINonConformityByLabno",
    title: "Study Nonconformity by Lab No.",
    group: "Study Nonconformity",
    source: "Study",
    route: "/StudyReport?type=patient&report=retroCINonConformityByLabno",
    kind: "by-lab-number",
    description: "Study nonconformity detail by accession range.",
  },
  {
    id: "retroCInonConformityNotification",
    title: "Nonconformity Notification",
    group: "Study Nonconformity",
    source: "Study",
    route: "/StudyReport?type=patient&report=retroCInonConformityNotification",
    kind: "nonconformity-notification",
    description: "Notification form using accession number and referring site.",
  },
  {
    id: "retroCIFollowupRequiredByLocation",
    title: "Follow-up Required by Location",
    group: "Study Nonconformity",
    source: "Study",
    route: "/StudyReport?type=patient&report=retroCIFollowupRequiredByLocation",
    kind: "intermediate-service",
    description: "Follow-up-required report by date range and location.",
  },
  {
    id: "CIStudyExport",
    title: "Study General Export",
    group: "Export by Date",
    source: "Study",
    route: "/StudyReport?type=patient&report=CIStudyExport",
    kind: "csv-export",
    description: "Study export by project and date type.",
  },
  {
    id: "Trends",
    title: "Viral Load Data Export",
    group: "Export by Date",
    source: "Study",
    route: "/StudyReport?type=patient&report=Trends",
    kind: "csv-export",
    description: "Viral-load trend export by study type and date range.",
  },
];

const sections = ["All", "Hematology", "Biochemistry", "Microbiology", "Serology", "Immunology"];
const priorities = ["Routine", "STAT", "Urgent"];
const timeFrames = ["Normal Work Hours (09:00-15:30)", "Out of Normal Work Hours (15:31-08:59)"];
const sidebarSectionMap: Record<string, { source?: "Routine" | "Study"; groups?: string[]; ids?: string[] }> = {
  Routine: { source: "Routine" },
  "Patient Status Report": { ids: ["patientCILNSP_vreduit"] },
  "Aggregate Reports": { source: "Routine", groups: ["Aggregate Reports", "Rejection Reports"] },
  "Activity Reports": { source: "Routine", groups: ["Activity Reports", "Delayed Validation"] },
  "Referred Tests": { ids: ["referredOut"] },
  "Non Conformity": { groups: ["Nonconformity Reports", "Study Nonconformity"] },
  "Routine CSV Report": { ids: ["CISampleRoutineExport"] },
  Study: { source: "Study" },
  "ARV Reports": { groups: ["ARV Reports"] },
  "EID Reports": { groups: ["EID Reports"] },
  "Viral Load": { ids: ["patientVL1", "Trends"] },
  "Export by Date": { groups: ["Export by Date"] },
  "Audit Trail": { ids: ["auditTrail"] },
};

const defaultReportBySidebarSection: Record<string, string> = {
  Routine: "patientCILNSP_vreduit",
  "Patient Status Report": "patientCILNSP_vreduit",
  "Aggregate Reports": "statisticsReport",
  "Activity Reports": "activityReportByTest",
  "Referred Tests": "referredOut",
  "Non Conformity": "haitiNonConformityByDate",
  "Routine CSV Report": "CISampleRoutineExport",
  Study: "patientARVInitial1",
  "ARV Reports": "patientARVInitial1",
  "EID Reports": "patientEID1",
  "Viral Load": "patientVL1",
  "Export by Date": "CIStudyExport",
  "Audit Trail": "auditTrail",
};

function Toggle({
  label,
  checked,
  onChange,
}: {
  label: string;
  checked: boolean;
  onChange: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onChange}
      className={cn(
        "rounded-md border px-3 py-2 text-left text-xs font-semibold transition-base",
        checked ? "border-primary bg-primary/10 text-primary" : "border-border bg-background text-muted-foreground hover:bg-secondary",
      )}
    >
      {label}
    </button>
  );
}

function SectionCard({
  title,
  children,
  action,
}: {
  title: string;
  children: React.ReactNode;
  action?: React.ReactNode;
}) {
  return (
    <section className="rounded-xl border border-border bg-card shadow-elegant">
      <div className="flex items-center justify-between gap-4 border-b border-border bg-gradient-surface px-6 py-4">
        <h2 className="text-lg font-semibold">{title}</h2>
        {action}
      </div>
      <div className="p-6">{children}</div>
    </section>
  );
}

function DateRangeFields() {
  return (
    <>
      <Field label="Start Date (lowerDateRange)">
        <Input type="date" defaultValue="2026-05-01" />
      </Field>
      <Field label="End Date (upperDateRange)">
        <Input type="date" defaultValue="2026-05-04" />
      </Field>
    </>
  );
}

function LabNumberFields() {
  return (
    <>
      <Field label="From Lab Number (accessionDirect)">
        <Input defaultValue="13022026-001" />
      </Field>
      <Field label="To Lab Number (highAccessionDirect)">
        <Input defaultValue="13022026-004" />
      </Field>
    </>
  );
}

function ReportCriteria({ report }: { report: ReportItem }) {
  const [onlyResults, setOnlyResults] = useState(true);
  const [selectedSections, setSelectedSections] = useState(["Hematology", "Biochemistry"]);
  const [selectedPriorities, setSelectedPriorities] = useState(["Routine"]);
  const [selectedFrames, setSelectedFrames] = useState([timeFrames[0]]);

  const switchValue = (value: string, values: string[], setValues: (values: string[]) => void) => {
    setValues(values.includes(value) ? values.filter((item) => item !== value) : [...values, value]);
  };

  if (report.kind === "statistics") {
    return (
      <div className="space-y-5">
        <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
          <Field label="Report Year (upperYear)">
            <Select defaultValue="2026">
              {["2026", "2025", "2024", "2023", "2022"].map((year) => (
                <option key={year}>{year}</option>
              ))}
            </Select>
          </Field>
        </div>
        <div className="grid grid-cols-1 gap-5 lg:grid-cols-3">
          <div>
            <p className="mb-2 text-xs font-bold uppercase tracking-wide text-muted-foreground">Lab Units (labSections)</p>
            <div className="grid grid-cols-2 gap-2">
              {sections.slice(1).map((section) => (
                <Toggle
                  key={section}
                  label={section}
                  checked={selectedSections.includes(section)}
                  onChange={() => switchValue(section, selectedSections, setSelectedSections)}
                />
              ))}
            </div>
          </div>
          <div>
            <p className="mb-2 text-xs font-bold uppercase tracking-wide text-muted-foreground">Priorities (priority)</p>
            <div className="grid grid-cols-1 gap-2">
              {priorities.map((priority) => (
                <Toggle
                  key={priority}
                  label={priority}
                  checked={selectedPriorities.includes(priority)}
                  onChange={() => switchValue(priority, selectedPriorities, setSelectedPriorities)}
                />
              ))}
            </div>
          </div>
          <div>
            <p className="mb-2 text-xs font-bold uppercase tracking-wide text-muted-foreground">Reception Time (receptionTime)</p>
            <div className="grid grid-cols-1 gap-2">
              {timeFrames.map((frame) => (
                <Toggle
                  key={frame}
                  label={frame}
                  checked={selectedFrames.includes(frame)}
                  onChange={() => switchValue(frame, selectedFrames, setSelectedFrames)}
                />
              ))}
            </div>
          </div>
        </div>
      </div>
    );
  }

  if (report.kind === "patient-status") {
    return (
      <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
        <Field label="Date Type (dateType)">
          <Select defaultValue="RESULT_DATE">
            <option value="RESULT_DATE">Result Date</option>
            <option value="ORDER_DATE">Order Date</option>
          </Select>
        </Field>
        <DateRangeFields />
        <LabNumberFields />
        <Field label="Patient (selPatient)">
          <Input placeholder="Search patient name or ID" />
        </Field>
        <Field label="Requester Site (referringSiteId)">
          <Input defaultValue="Central Hospital" />
        </Field>
        <Field label="Requester Department (referringSiteDepartmentId)">
          <Select defaultValue="All">
            <option>All</option>
            <option>OPD</option>
            <option>Emergency</option>
            <option>ART Clinic</option>
          </Select>
        </Field>
        <label className="flex items-center gap-2 rounded-md border border-border bg-background px-3 py-2 text-sm font-semibold">
          <input type="checkbox" checked={onlyResults} onChange={() => setOnlyResults(!onlyResults)} />
          Only samples with results (onlyResults / _onlyResults)
        </label>
      </div>
    );
  }

  if (report.kind === "by-lab-number") {
    return (
      <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
        <LabNumberFields />
      </div>
    );
  }

  if (report.kind === "by-patient-id") {
    return (
      <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
        <Field label="National / Patient ID (patientNumberDirect)">
          <Input defaultValue="SDH21082" />
        </Field>
      </div>
    );
  }

  if (report.kind === "referred-out" || report.kind === "intermediate-service") {
    return (
      <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
        <DateRangeFields />
        <Field label={report.kind === "referred-out" ? "Referral Organization (locationCode)" : "Requester / Service Location (locationCode)"}>
          <Select defaultValue="Central Hospital">
            <option>Central Hospital</option>
            <option>District Public Health Lab</option>
            <option>ART Clinic</option>
            <option>External Referral Lab</option>
          </Select>
        </Field>
      </div>
    );
  }

  if (report.kind === "csv-export") {
    return (
      <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
        <DateRangeFields />
        <Field label={report.id === "CIStudyExport" ? "Project (projectCode)" : "Study Type (vlStudyType)"}>
          <Select defaultValue="VL">
            <option value="VL">Viral Load</option>
            <option value="ARV">ARV</option>
            <option value="EID">EID</option>
            <option value="CI">Clinical Investigation</option>
          </Select>
        </Field>
        {report.id === "CIStudyExport" && (
          <Field label="Date Type (dateType)">
            <Select defaultValue="RECEIVED_DATE">
              <option value="RECEIVED_DATE">Received Date</option>
              <option value="RESULT_DATE">Result Date</option>
              <option value="VALIDATION_DATE">Validation Date</option>
            </Select>
          </Field>
        )}
      </div>
    );
  }

  if (report.kind === "audit-trail") {
    return (
      <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
        <Field label="Accession Number (accessionNumber)">
          <Input defaultValue="13022026-004" />
        </Field>
      </div>
    );
  }

  if (report.kind === "nonconformity-notification") {
    return (
      <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
        <Field label="Lab Number (accessionDirect)">
          <Input defaultValue="13022026-003" />
        </Field>
        <Field label="Referring Site (selectList.selection)">
          <Input defaultValue="Emergency Department" />
        </Field>
      </div>
    );
  }

  return (
    <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
      <DateRangeFields />
      <Field label="Selection (selectList.selection)">
        <Select>
          {report.id === "activityReportByPanel" ? (
            <>
              <option>All Panels</option>
              <option>CBC</option>
              <option>LFT</option>
              <option>HIV Viral Load</option>
            </>
          ) : report.id === "activityReportByTest" ? (
            <>
              <option>All Tests</option>
              <option>Hemoglobin</option>
              <option>Glucose</option>
              <option>VDRL</option>
            </>
          ) : (
            sections.map((section) => <option key={section}>{section}</option>)
          )}
        </Select>
      </Field>
    </div>
  );
}

function ReportPreview({ report }: { report: ReportItem }) {
  if (report.kind === "audit-trail") {
    return (
      <table className="w-full text-sm">
        <thead className="bg-muted/40 text-left text-[11px] uppercase tracking-wider text-muted-foreground">
          <tr>
            <th className="px-6 py-3 font-semibold">Time</th>
            <th className="px-6 py-3 font-semibold">User</th>
            <th className="px-6 py-3 font-semibold">Action</th>
            <th className="px-6 py-3 font-semibold">Field</th>
            <th className="px-6 py-3 font-semibold">Value</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-border">
          {[
            ["09:18", "admin", "Result updated", "Glucose", "142 mg/dL"],
            ["09:42", "supervisor", "Validated", "Validation", "Supervisor Validation"],
            ["10:03", "admin", "Report printed", "Format", "PDF"],
          ].map((row) => (
            <tr key={row.join("-")} className="h-14 transition-base hover:bg-secondary/40">
              {row.map((cell, index) => (
                <td key={cell} className={cn("px-6", index === 2 && "font-semibold text-primary")}>
                  {cell}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    );
  }

  return (
    <table className="w-full text-sm">
      <thead className="bg-muted/40 text-left text-[11px] uppercase tracking-wider text-muted-foreground">
        <tr>
          <th className="px-6 py-3 font-semibold">Report</th>
          <th className="px-6 py-3 font-semibold">Patient / Group</th>
          <th className="px-6 py-3 font-semibold">Accession</th>
          <th className="px-6 py-3 font-semibold">Section</th>
          <th className="px-6 py-3 font-semibold">Status</th>
          <th className="px-6 py-3 font-semibold">Generated</th>
        </tr>
      </thead>
      <tbody className="divide-y divide-border">
        {SAMPLES.slice(0, 6).map((sample, index) => (
          <tr key={`${report.id}-${sample.accession}`} className="h-14 transition-base hover:bg-secondary/40">
            <td className="px-6 font-semibold text-primary">{report.title}</td>
            <td className="px-6">
              <div className="font-semibold">{report.source === "Study" ? sample.patient : sample.panel}</div>
              <div className="text-xs text-muted-foreground">{sample.patientId}</div>
            </td>
            <td className="px-6">{sample.accession}</td>
            <td className="px-6">{sample.section}</td>
            <td className="px-6">
              <Badge value={index % 3 === 0 ? "Validated" : sample.status} />
            </td>
            <td className="px-6">04/05/2026</td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}

function iconFor(kind: ReportKind) {
  if (kind === "statistics") return BarChart3;
  if (kind === "csv-export") return FileSpreadsheet;
  if (kind === "audit-trail") return History;
  if (kind === "by-date") return Activity;
  if (kind === "patient-status") return ClipboardList;
  return FileText;
}

export function Reports({
  reportSection = "Patient Status Report",
  setReportSection,
}: {
  reportSection?: string;
  setReportSection?: (v: string) => void;
}) {
  const [selectedId, setSelectedId] = useState("patientCILNSP_vreduit");

  const visibleReports = useMemo(() => {
    const filter = sidebarSectionMap[reportSection] ?? sidebarSectionMap["Patient Status Report"];
    return REPORTS.filter((report) => {
      const matchesSource = !filter.source || report.source === filter.source;
      const matchesGroup = !filter.groups || filter.groups.includes(report.group);
      const matchesId = !filter.ids || filter.ids.includes(report.id);
      return matchesSource && matchesGroup && matchesId;
    });
  }, [reportSection]);

  const defaultId = defaultReportBySidebarSection[reportSection] ?? "patientCILNSP_vreduit";
  const selectedReport =
    visibleReports.find((report) => report.id === selectedId) ??
    visibleReports.find((report) => report.id === defaultId) ??
    visibleReports[0] ??
    REPORTS[0];
  const SourceIcon = selectedReport.source === "Routine" ? ClipboardList : FileText;

  return (
    <PageWrap>
      <div className="mb-6 flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Reports</h1>
          <p className="mt-1.5 max-w-3xl text-sm text-muted-foreground">
            {reportSection} reports with OpenELIS Global filters, printable outputs, CSV exports, and audit views.
          </p>
        </div>
        <div className="flex gap-2">
          <GhostButton>
            <Download className="h-4 w-4" /> Export CSV
          </GhostButton>
          <PrimaryButton>
            <Printer className="h-4 w-4" /> Generate Printable Version
          </PrimaryButton>
        </div>
      </div>

      <div className="mb-6 grid grid-cols-1 gap-4 md:grid-cols-4">
        {[
          ["35", "Report templates", "text-primary"],
          ["14", "Routine reports", "text-success"],
          ["21", "Study reports", "text-info"],
          ["7", "Export / audit flows", "text-warning"],
        ].map(([value, label, tone]) => (
          <section key={label} className="rounded-xl border border-border bg-card p-5 shadow-elegant">
            <div className={cn("text-2xl font-bold", tone)}>{value}</div>
            <div className="mt-1 text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</div>
          </section>
        ))}
      </div>

      <div className="space-y-6">
        {visibleReports.length > 1 && (
          <section className="rounded-xl border border-border bg-card p-3 shadow-elegant">
            <div className="flex flex-wrap gap-2">
              {visibleReports.map((report) => {
                const Icon = iconFor(report.kind);
                return (
                  <button
                    key={report.id}
                    type="button"
                    onClick={() => {
                      setSelectedId(report.id);
                      setReportSection?.(reportSection);
                    }}
                    className={cn(
                      "inline-flex items-center gap-2 rounded-md border px-3 py-2 text-xs font-bold transition-base",
                      selectedReport.id === report.id
                        ? "border-primary bg-primary/10 text-primary"
                        : "border-border bg-background text-muted-foreground hover:bg-secondary hover:text-foreground",
                    )}
                  >
                    <Icon className="h-4 w-4" />
                    {report.title}
                  </button>
                );
              })}
            </div>
          </section>
        )}

        <SectionCard
          title={selectedReport.title}
          action={
            <span className="inline-flex items-center gap-2 rounded-full border border-border bg-background px-3 py-1 text-xs font-bold text-muted-foreground">
              <SourceIcon className="h-3.5 w-3.5" /> {selectedReport.source} / {selectedReport.group}
            </span>
          }
        >
          <div className="mb-5 rounded-lg border border-border bg-secondary/50 p-4">
            <p className="text-sm font-semibold text-foreground">{selectedReport.description}</p>
            <p className="mt-1 text-xs text-muted-foreground">OpenELIS route: {selectedReport.route}</p>
          </div>
          <ReportCriteria report={selectedReport} />
          <div className="mt-6 flex flex-wrap justify-end gap-3">
            <GhostButton>Clear</GhostButton>
            <GhostButton>
              <FileSpreadsheet className="h-4 w-4" /> Preview Data
            </GhostButton>
            <PrimaryButton>
              <Printer className="h-4 w-4" /> Generate Printable Version
            </PrimaryButton>
          </div>
        </SectionCard>

        <SectionCard
          title="Static Report Preview"
          action={
            <div className="flex gap-2">
              <button className="rounded-md border border-border bg-background px-3 py-1.5 text-xs font-bold text-foreground transition-base hover:bg-secondary">
                CSV
              </button>
              <button className="rounded-md border border-border bg-background px-3 py-1.5 text-xs font-bold text-foreground transition-base hover:bg-secondary">
                PDF
              </button>
            </div>
          }
        >
          <div className="-m-6 overflow-x-auto">
            <ReportPreview report={selectedReport} />
          </div>
        </SectionCard>
      </div>
    </PageWrap>
  );
}
